Add Glow Sign In buttons
glow-xyz/glow-js pull request #2
Opened 2022-04-21 12:00 UTC by MeLlamoPablo

![image](https://user-images.githubusercontent.com/11708035/164453371-2ee219d6-f49b-4805-b048-339da9a34191.png)

This PR adds `GlowSignInButton` to `example-next-js`. The button can be customized with the following props:

* Size: `lg`, `md`, `sm`
* Shape: `squared`, `rounded`
* Variant: `black`, `purple`, `white-naked`, `white-outline`

You can try them at http://localhost:3000/buttons

2022-04-21 14:32 UTC, MeLlamoPablo commented
@vpontis can't add you as reviewer, pinging you here

2022-04-21 15:16 UTC, vpontis requested changes
Thanks @MeLlamoPablo! You should have elevated permissions in this repo now.

Where did you get the idea for the shadow on hover from? If you look at the Figma, the bottom state is supposed to be the hover state (it's labeled if you look at the frame names):

<img width="900" alt="CleanShot 2022-04-21 at 11 15 37@2x" src="https://user-images.githubusercontent.com/1319079/164490301-9db76344-51cc-4203-a1fe-4b3839ed9122.png">
<img width="268" alt="CleanShot 2022-04-21 at 11 16 07@2x" src="https://user-images.githubusercontent.com/1319079/164490329-21b2721a-cb7f-4b06-824b-3a1f1160aaec.png">

2022-04-21 15:16 UTC, vpontis commented on packages/example-next-js/pages/buttons.tsx
> +import styles from "../styles/Buttons.module.scss";
Haha I find CSS modules pretty frustrating in terms of DX. But it's fine since this isn't what we are going to publish for reuse.

2022-04-21 16:55 UTC, MeLlamoPablo commented
I didn't see the labels! Removed the disabled buttons from the example page and made the change.

![Screenshot 2022-04-21 at 18 53 54](https://user-images.githubusercontent.com/11708035/164511627-0cac2bb4-6af5-4057-a09d-9aaa9aa600fa.png)

Then I don't understand the shadow. In Figma only the button in the top left has it, but the rests of its kind don't. Maybe it's another customizable prop? Or it's a shadow on click?

2022-04-21 19:09 UTC, vpontis commented
Shadow — let's leave it off for now.

Hmmm the hover states don't look quite right

<img width="447" alt="CleanShot 2022-04-21 at 15 09 07@2x" src="https://user-images.githubusercontent.com/1319079/164535434-74a66485-1694-4f8f-bdd2-3e4cedb4f0da.png">
<img width="272" alt="CleanShot 2022-04-21 at 15 09 02@2x" src="https://user-images.githubusercontent.com/1319079/164535445-f9882665-6020-436f-905f-9438e1f4d457.png">

Let's match what we have in Figma.

2022-04-21 19:10 UTC, vpontis requested changes
Requesting changes re design

2022-04-22 08:45 UTC, MeLlamoPablo commented
Made some polish and added the 3D Glow icon, I didn't realize the icons were different.

> Hmmm the hover states don't look quite right
> 
> <img alt="CleanShot 2022-04-21 at 15 09 07@2x" width="447" src="https://user-images.githubusercontent.com/1319079/164535434-74a66485-1694-4f8f-bdd2-3e4cedb4f0da.png">
> 
> <img alt="CleanShot 2022-04-21 at 15 09 02@2x" width="272" src="https://user-images.githubusercontent.com/1319079/164535445-f9882665-6020-436f-905f-9438e1f4d457.png">
> 
> Let's match what we have in Figma.

If I copy what Figma says which is:

```css
background: linear-gradient(93deg, rgba(209, 64, 221, 0.7) 1.51%, rgba(161, 38, 209, 0.7) 99.28%), #FFFFFF;
box-shadow: inset 0px 0px 44.9123px rgba(0, 0, 0, 0.5);
```

I get:

![Screenshot 2022-04-22 at 10 44 07](https://user-images.githubusercontent.com/11708035/164652467-51dcbff5-4eca-4ea8-8b87-56cc5a7fbbbb.png)

I tried to make it look as close as it looks. Any other ideas?

2022-04-25 04:22 UTC, vpontis commented
@MeLlamoPablo btw I didn't get to this over the weekend so I focused the Twitch stream stuff on the Solana program :)

2022-04-25 13:10 UTC, MeLlamoPablo commented
Let me know if it looks better now!

PR Regular:

<img width="276" alt="Screenshot 2022-04-25 at 15 09 53" src="https://user-images.githubusercontent.com/11708035/165095616-e9fdeb12-0bd0-436c-bf78-fb67ba8affef.png">

PR Hover:

<img width="276" alt="Screenshot 2022-04-25 at 15 09 35" src="https://user-images.githubusercontent.com/11708035/165095573-efc88061-7d48-48dc-8768-e1a34b73a3bd.png">

Figma Hover:

<img width="276" alt="Screenshot 2022-04-25 at 15 04 59" src="https://user-images.githubusercontent.com/11708035/165094897-bbc70e87-d0e8-4259-8e7c-931245754371.png">

2022-04-25 17:36 UTC, vpontis commented
Hmm it still feels a bit off and there is no animation

2022-04-25 19:56 UTC, MeLlamoPablo commented
Could you point specifically what feels off about it? I've tried but I think that's the best I can do.

Regarding the animation, [gradient background transitions don't work out of the box](https://stackoverflow.com/questions/6542212/use-css3-transitions-with-gradient-backgrounds). I've been trying the workaround with `::before`, I'll keep trying tomorrow.

2022-05-02 04:31 UTC, vpontis commented
> Could you point specifically what feels off about it? I've tried but I think that's the best I can do.
> 
> Regarding the animation, [gradient background transitions don't work out of the box](https://stackoverflow.com/questions/6542212/use-css3-transitions-with-gradient-backgrounds). I've been trying the workaround with `::before`, I'll keep trying tomorrow.

Let's get the animation working and then we can merge this in.

2022-05-04 16:26 UTC, MeLlamoPablo commented
https://user-images.githubusercontent.com/11708035/166726435-b5e58874-6a90-4c3b-bcba-db2c88341814.mov

Manged to make the animation work using an absolutely positioned layer with animated opacity. I don't like that it makes the HTML and CSS more complex, but it should work across all browsers unlike the `@property` solution.

Let me know if there's something else I can do!

2022-05-04 17:39 UTC, vpontis commented
Awesome, thanks @MeLlamoPablo 👍👍. I'll approve

For the next PR, can we move the buttons from `next-js` → the React package?

2022-05-04 17:39 UTC, vpontis approved these changes

2022-05-04 17:48 UTC, merged