[wip] Changes for web3.js migration
glow-xyz/glow-js pull request #74
Opened 2022-09-15 13:42 UTC by sjchmiela

- [Loom (3 min)](https://www.loom.com/share/8c22ec0de8e7497d910bc31b2e761a3e)

2022-09-15 14:47 UTC, vpontis approved these changes

2022-09-15 14:47 UTC, vpontis commented on packages/solana-client/src/GTransaction.ts
> +    const unsignedTransaction = create({
It would be nice if we had an easier way of copying txs but let's not change that in this PR.

2022-09-15 14:47 UTC, vpontis requested changes
I'm a bit confused re `null` signatures. Why do we need to allow that?

2022-09-15 14:54 UTC, sjchmiela commented
Mainly for coherence. Right now on `master` for a given snippet:

```ts
const original = GTransaction.create({ ..., signers: [] }); // { signatures: [{ address: "sth", signature: null }] }
const originalSerialized = GTransaction.toBuffer({ gtransaction: original });
const originalDeserialized = GTransaction.parse({ buffer: originalSerialized }); // { signatures: [{ address: "sth", signature: "1111" }] }
```

whereas the only thing we did was serialize and deserialize.

Another reason I mentioned is "compatibility" with `@solana/web3.js` API where they do exactly that — [parse `1111` signatures as `null`](https://github.com/solana-labs/solana/blob/bac6ebcd8814f35ba23bb2690895b27f84da494e/web3.js/src/transaction/legacy.ts#L828-L831) and we depend on it (at least) [here](https://github.com/luma-team/luma/blob/43f860500f2a854b9ff960a75225122556772d22/server/src/routes/solana-pay.ts#L30).

2022-09-15 14:58 UTC, vpontis commented
> Mainly for coherence. Right now on `master` for a given snippet:
> 
> ```ts
> const original = GTransaction.create({ ..., signers: [] }); // { signatures: [{ address: "sth", signature: null }] }
> const originalSerialized = GTransaction.toBuffer({ gtransaction: original });
> const originalDeserialized = GTransaction.parse({ buffer: originalSerialized }); // { signatures: [{ address: "sth", signature: "1111" }] }
> ```
> 
> signatures are not equal anymore while the only thing we did was serialize and deserialize.
> 
> Another reason I mentioned is "compatibility" with `@solana/web3.js` API where they do exactly that — [parse `1111` signatures as `null`](https://github.com/solana-labs/solana/blob/bac6ebcd8814f35ba23bb2690895b27f84da494e/web3.js/src/transaction/legacy.ts#L828-L831) and we depend on it (at least) [here](https://github.com/luma-team/luma/blob/43f860500f2a854b9ff960a75225122556772d22/server/src/routes/solana-pay.ts#L30).

Hmm, can we not include the `null` change in this PR? I'm not convinced we need it yet. I can play around w/ our codebase to see how we can work around it. 

I don't think we need full compatibility w/ web3.js unless I'm missing something.

2022-09-15 15:12 UTC, sjchmiela commented
Sure. The workaround for this is to instead of checking `signature === null` do:

```
signature === null || bs58.decode(signature).every(byte => byte === 0)
```

which felt inconvenient to me.

I agree we don't need full compatibility with web3.js, which is why I mentioned it as second, extra argument. The main reasons I think this change is nice is convenience (shown above) and equality between original and reserialized transactions.

2022-09-16 01:59 UTC, vpontis approved these changes

2022-09-16 02:01 UTC, vpontis commented on packages/solana-client/src/GTransaction.ts
> +  !signature || bs58.decode(signature).every((byte) => byte === 0);
Hmm, I don't think we need to decode here. I think it'll just be all `1`s

2022-09-16 05:02 UTC, merged